// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;


namespace Model;

public partial class OrderItem
{
    [Required(ErrorMessage = "OrderItemId ID is required")]
    public int OrderItemId { get; set; }

    [Required(ErrorMessage = "Order ID is required")]
    public int OrderId { get; set; }
    [Required(ErrorMessage = "Product ID is required")]
    public int? ProductId { get; set; }

    [Range(1, int.MaxValue, ErrorMessage = "Quantity must be at least 1")]
    public int? Quantity { get; set; }

    public virtual Order Order { get; set; }

    public virtual Product Product { get; set; }
}