// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Model;

public partial class Product
{
    public int ProductId { get; set; }

    public string Name { get; set; }

    public int? CategoryId { get; set; }

    public int? Price { get; set; }

    public string Description { get; set; }

    public string ImageUrl { get; set; }

    public virtual Category Category { get; set; }

    public virtual ICollection<OrderItem> OrderItems { get; set; } = new List<OrderItem>();
}