// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Model;

public partial class Product
{
    [Required(ErrorMessage = "ProductId is required")]
    public int ProductId { get; set; }

    public string Name { get; set; }
    [Required(ErrorMessage = "CategoryId is required")]
    public int? CategoryId { get; set; }

    [Range(0, int.MaxValue, ErrorMessage = "Price must be bigger than 0")]
    public int? Price { get; set; }

    public string Description { get; set; }

    public string ImageUrl { get; set; }

    public virtual Category Category { get; set; }

    public virtual ICollection<OrderItem> OrderItems { get; set; } = new List<OrderItem>();
}