// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Model;

public partial class User
{
    public int UserId { get; set; }

    public string Gmail { get; set; }

    public string UserFirstName { get; set; }

    public string UserLastname { get; set; }

    public string Password { get; set; }

    public virtual ICollection<Order> Orders { get; set; } = new List<Order>();
}